/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Brand colors
        primary: {
          50: 'var(--color-brand-primary-50)',
          100: 'var(--color-brand-primary-100)',
          200: 'var(--color-brand-primary-200)',
          300: 'var(--color-brand-primary-300)',
          400: 'var(--color-brand-primary-400)',
          500: 'var(--color-brand-primary-500)',
          600: 'var(--color-brand-primary-600)',
          700: 'var(--color-brand-primary-700)',
          800: 'var(--color-brand-primary-800)',
          900: 'var(--color-brand-primary-900)',
          DEFAULT: 'var(--color-brand-primary-500)',
          foreground: '#ffffff',
        },
        secondary: {
          50: 'var(--color-brand-secondary-50)',
          100: 'var(--color-brand-secondary-100)',
          200: 'var(--color-brand-secondary-200)',
          300: 'var(--color-brand-secondary-300)',
          400: 'var(--color-brand-secondary-400)',
          500: 'var(--color-brand-secondary-500)',
          600: 'var(--color-brand-secondary-600)',
          700: 'var(--color-brand-secondary-700)',
          800: 'var(--color-brand-secondary-800)',
          900: 'var(--color-brand-secondary-900)',
          DEFAULT: 'var(--color-brand-secondary-500)',
          foreground: '#ffffff',
        },
        // Neutral colors
        neutral: {
          50: 'var(--color-neutral-grey-50)',
          100: 'var(--color-neutral-grey-100)',
          200: 'var(--color-neutral-grey-200)',
          300: 'var(--color-neutral-grey-300)',
          400: 'var(--color-neutral-grey-400)',
          500: 'var(--color-neutral-grey-500)',
          600: 'var(--color-neutral-grey-600)',
          700: 'var(--color-neutral-grey-700)',
          800: 'var(--color-neutral-grey-800)',
          900: 'var(--color-neutral-grey-900)',
          950: 'var(--color-neutral-grey-950)',
        },
        // Signal colors
        success: {
          500: 'var(--color-signal-success-500)',
          600: 'var(--color-signal-success-600)',
          DEFAULT: 'var(--color-signal-success-500)',
        },
        warning: {
          500: 'var(--color-signal-warning-500)',
          600: 'var(--color-signal-warning-600)',
          DEFAULT: 'var(--color-signal-warning-500)',
        },
        error: {
          500: 'var(--color-signal-error-500)',
          600: 'var(--color-signal-error-600)',
          DEFAULT: 'var(--color-signal-error-500)',
        },
        destructive: {
          DEFAULT: 'var(--color-signal-error-500)',
          foreground: '#ffffff',
        },
        info: {
          500: 'var(--color-signal-info-500)',
          600: 'var(--color-signal-info-600)',
          DEFAULT: 'var(--color-signal-info-500)',
        },
        // Surface colors
        background: 'var(--color-surface-base)',
        surface: {
          base: 'var(--color-surface-base)',
          1: 'var(--color-surface-level-1)',
          2: 'var(--color-surface-level-2)',
          3: 'var(--color-surface-level-3)',
          action: 'var(--color-surface-action)',
          disabled: 'var(--color-surface-disabled)',
        },
        // Content colors
        foreground: 'var(--color-content-primary)',
        content: {
          primary: 'var(--color-content-primary)',
          subtle: 'var(--color-content-subtle)',
          muted: 'var(--color-content-muted)',
          action: 'var(--color-content-action)',
          'on-action': 'var(--color-content-on-action)',
          disabled: 'var(--color-content-disabled)',
        },
        // Border colors (semantic)
        'border-action': 'var(--color-border-action)',
        'border-disabled': 'var(--color-border-disabled)',
        // shadcn/ui compatibility aliases
        border: 'var(--color-border-default)',
        input: 'var(--color-neutral-grey-200)',
        ring: 'var(--color-brand-primary-500)',
        muted: {
          DEFAULT: 'var(--color-neutral-grey-100)',
          foreground: 'var(--color-content-muted)',
        },
        accent: {
          DEFAULT: 'var(--color-neutral-grey-100)',
          foreground: 'var(--color-content-primary)',
        },
      },
      spacing: {
        0: 'var(--spacing-0)',
        1: 'var(--spacing-4)',
        2: 'var(--spacing-8)',
        3: 'var(--spacing-12)',
        4: 'var(--spacing-16)',
        5: 'var(--spacing-20)',
        6: 'var(--spacing-24)',
        8: 'var(--spacing-32)',
        10: 'var(--spacing-40)',
        12: 'var(--spacing-48)',
        16: 'var(--spacing-64)',
        20: 'var(--spacing-80)',
        24: 'var(--spacing-96)',
      },
      borderRadius: {
        none: 'var(--border-radius-none)',
        sm: 'var(--border-radius-sm)',
        DEFAULT: 'var(--border-radius-md)',
        md: 'var(--border-radius-md)',
        lg: 'var(--border-radius-lg)',
        xl: 'var(--border-radius-xl)',
      },
      borderWidth: {
        0: 'var(--border-width-none)',
        DEFAULT: 'var(--border-width-thin)',
        thin: 'var(--border-width-thin)',
        medium: 'var(--border-width-medium)',
        thick: 'var(--border-width-thick)',
      },
      borderColor: {
        DEFAULT: 'var(--color-border-default)',
        action: 'var(--color-border-action)',
        disabled: 'var(--color-border-disabled)',
      },
      fontFamily: {
        heading: ['var(--typography-font-family-heading)', 'system-ui', 'sans-serif'],
        body: ['var(--typography-font-family-body)', 'system-ui', 'sans-serif'],
        mono: ['var(--typography-font-family-mono)', 'monospace'],
        sans: ['var(--typography-font-family-body)', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        xs: ['var(--typography-font-size-xs)', { lineHeight: 'var(--typography-line-height-4)' }],
        sm: ['var(--typography-font-size-sm)', { lineHeight: 'var(--typography-line-height-4)' }],
        base: ['var(--typography-font-size-base)', { lineHeight: 'var(--typography-line-height-5)' }],
        lg: ['var(--typography-font-size-lg)', { lineHeight: 'var(--typography-line-height-5)' }],
        xl: ['var(--typography-font-size-xl)', { lineHeight: 'var(--typography-line-height-6)' }],
        '2xl': ['var(--typography-font-size-2xl)', { lineHeight: 'var(--typography-line-height-6)' }],
        '3xl': ['var(--typography-font-size-3xl)', { lineHeight: 'var(--typography-line-height-relaxed)' }],
        '4xl': ['var(--typography-font-size-4xl)', { lineHeight: 'var(--typography-line-height-tight)' }],
        '5xl': ['var(--typography-font-size-5xl)', { lineHeight: 'var(--typography-line-height-tight)' }],
      },
      fontWeight: {
        normal: 'var(--typography-font-weight-normal)',
        medium: 'var(--typography-font-weight-medium)',
        semibold: 'var(--typography-font-weight-semibold)',
        bold: 'var(--typography-font-weight-bold)',
      },
      lineHeight: {
        none: 'var(--typography-line-height-none)',
        tight: 'var(--typography-line-height-tight)',
        snug: 'var(--typography-line-height-snug)',
        normal: 'var(--typography-line-height-normal)',
        relaxed: 'var(--typography-line-height-relaxed)',
        loose: 'var(--typography-line-height-loose)',
        4: 'var(--typography-line-height-4)',
        5: 'var(--typography-line-height-5)',
        6: 'var(--typography-line-height-6)',
      },
    },
  },
  plugins: [],
}
