import figma from "@figma/code-connect";
import { Button } from "./button";

/**
 * -- This file was auto-generated by Code Connect --
 * 
 * This file connects the Button component to its Figma design.
 * To use this, you need to:
 * 1. Get the Figma node ID from your Figma file (right-click component > Copy link > extract ID)
 * 2. Replace 'NODE_ID_HERE' below with your actual Figma component node ID
 * 3. Ensure the variant mappings match your Figma component variants
 */

figma.connect(
  Button,
  "https://www.figma.com/design/XIDqnN4PNwZqsOd2cG0Avq/Design-System?node-id=33-185",
  {
    props: {
      type: figma.enum("type", {
        default: "default",
        outline: "outline",
        transparent: "transparent",
      }),
      status: figma.enum("status", {
        default: "default",
        hover: "hover",
        focus: "focus",
        disabled: "disabled",
      }),
      label: figma.string("Label"),
      iconLeft: figma.boolean("Icon left"),
      iconRight: figma.boolean("Icon right"),
    },
    example: (props) => (
      <Button
        variant={props.type === "outline" ? "outline" : props.type === "transparent" ? "ghost" : "default"}
        disabled={props.status === "disabled"}
      >
        {props.label}
      </Button>
    ),
  }
);
