import figma from "@figma/code-connect";
import { 
  Card, 
  CardHeader, 
  CardTitle, 
  CardDescription, 
  CardContent, 
  CardFooter 
} from "./card";

/**
 * -- This file was auto-generated by Code Connect --
 * 
 * This file connects the Card component to its Figma design.
 * Updated to match the actual Figma component structure.
 */

figma.connect(
  Card,
  "https://www.figma.com/design/XIDqnN4PNwZqsOd2cG0Avq/Design-System?node-id=70-46",
  {
    props: {
      title: figma.children("Card Title"),
      content: figma.children("card contents"),
    },
    example: (props) => (
      <Card>
        <CardHeader>
          <CardTitle>{props.title}</CardTitle>
        </CardHeader>
        <CardContent>
          {props.content}
        </CardContent>
      </Card>
    ),
  }
);
